#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "usage:   install_existing_linux [path-to-root-of-minetest-files]"
fi

cp -R Parade_Server_World $1/worlds
cp -R parade_server $1/games/mcr_coderdojo/mods

echo Files copied to $1.  Please re-start Minetest to play