#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "usage:   install_existing_linux [path-to-root-of-minetest-files]"
fi

mkdir --parents $1/games
mkdir --parents $1/worlds

cp -R mcr_coderdojo $1/games/mcr_coderdojo
cp -R Parade_Client_World $1/worlds/Parade_Client_World

echo Files copied to $1.  Please re-start Minetest to play
