# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo Installing Minetest
sudo add-apt-repository -y  ppa:minetestdevs/stable
sudo apt-get -y update
sudo apt-get -y install Minetest
echo Linking the Manchester CoderDojo game
sudo ln -s /vagrant/mcr_coderdojo /usr/share/minetest/games/mcr_coderdojo
mkdir --parents /home/vagrant/.minetest/worlds
ln -s /vagrant/Parade_Client_World /home/vagrant/.minetest/worlds/Parade_Client_World
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "npalm/mint17-amd64-cinnamon"  
  config.vm.provision "shell", inline: $script
  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = 2048
     vb.cpus = 1
     vb.customize ["modifyvm", :id, "--vram", "100"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end
  
end
